// The Modified BSD License
//
// Copyright (c) 2015, Mikhail Balakhno
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// * Redistributions of source code must retain the above copyright notice, this
//   list of conditions and the following disclaimer.
//
// * Redistributions in binary form must reproduce the above copyright notice,
//   this list of conditions and the following disclaimer in the documentation
//   and/or other materials provided with the distribution.
//
// * Neither the name of fontio nor the names of its
//   contributors may be used to endorse or promote products derived from
//   this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#include <fontio/model/UtfEncoding.hpp>

namespace fontio { namespace model
{
    std::unordered_map<std::string, uint16_t> UtfEncoding::glyphs =
    {
        { "A", 0x41 },
        { "a", 0x61 },
        { "acute", 0x00B4 },
        { "AE", 0x00C6 },
        { "ae", 0x0 },
        { "ampersand", 0x26 },
        { "asciicircum", 0x005E },
        { "asciitilde", 0x007E },
        { "asterisk", 0x002A },
        { "at", 0x40 },
        { "B", 0x42 },
        { "b", 0x62 },
        { "backslash", 0x005C },
        { "bar", 0x007C },
        { "braceleft", 0x007B },
        { "braceright", 0x007D },
        { "bracketleft", 0x005B },
        { "bracketright", 0x005D },
        { "breve", 0x02D8 },
        { "bullet", 0x2022 },
        { "C", 0x43 },
        { "c", 0x63 },
        { "caron", 0x02C7 },
        { "cedilla", 0x00B8 },
        { "cent", 0x00A2 },
        { "circumflex", 0x02C6 },
        { "colon", 0x003A },
        { "comma", 0x002C },
        { "currency", 0x00A4 },
        { "D", 0x44 },
        { "d", 0x64 },
        { "dagger", 0x2020 },
        { "daggerdbl", 0x2021 },
        { "dieresis", 0x00A8 },
        { "dollar", 0x24 },
        { "dotaccent", 0x02D9 },
        { "dotlessi", 0x131 },
        { "E", 0x45 },
        { "e", 0x65 },
        { "eight", 0x38 },
        { "ellipsis", 0x2026 },
        { "emdash", 0x2014 },
        { "endash", 0x2013 },
        { "equal", 0x003D },
        { "exclam", 0x21 },
        { "exclamdown", 0x00A1 },
        { "F", 0x46 },
        { "f", 0x66 },
        { "fi", 0xFB01 },
        { "five", 0x35 },
        { "fl", 0xFB02 },
        { "florin", 0x192 },
        { "four", 0x34 },
        { "fraction", 0x2044 },
        { "fraction", 0x2215 },
        { "G", 0x47 },
        { "g", 0x67 },
        { "germandbls", 0x00DF },
        { "grave", 0x60 },
        { "greater", 0x003E },
        { "guillemotleft", 0x00AB },
        { "guillemotright", 0x00BB },
        { "guilsinglleft", 0x2039 },
        { "guilsinglright", 0x203A },
        { "H", 0x48 },
        { "h", 0x68 },
        { "hungarumlaut", 0x02DD },
        { "hyphen", 0x002D },
        { "hyphen", 0x00AD },
        { "I", 0x49 },
        { "i", 0x69 },
        { "J", 0x004A },
        { "j", 0x006A },
        { "K", 0x004B },
        { "k", 0x006B },
        { "L", 0x004C },
        { "l", 0x006C },
        { "less", 0x003C },
        { "Lslash", 0x141 },
        { "lslash", 0x142 },
        { "M", 0x004D },
        { "m", 0x006D },
        { "macron", 0x00AF },
        { "macron", 0x02C9 },
        { "N", 0x004E },
        { "n", 0x006E },
        { "nine", 0x39 },
        { "numbersign", 0x23 },
        { "O", 0x004F },
        { "o", 0x006F },
        { "OE", 0x152 },
        { "oe", 0x153 },
        { "ogonek", 0x02DB },
        { "one", 0x31 },
        { "ordfeminine", 0x00AA },
        { "ordmasculine", 0x00BA },
        { "Oslash", 0x00D8 },
        { "oslash", 0x00F8 },
        { "P", 0x50 },
        { "p", 0x70 },
        { "paragraph", 0x00B6 },
        { "parenleft", 0x28 },
        { "parenright", 0x29 },
        { "percent", 0x25 },
        { "period", 0x002E },
        { "periodcentered", 0x00B7 },
        { "periodcentered", 0x2219 },
        { "perthousand", 0x2030 },
        { "plus", 0x002B },
        { "Q", 0x51 },
        { "q", 0x71 },
        { "question", 0x003F },
        { "questiondown", 0x00BF },
        { "quotedbl", 0x22 },
        { "quotedblbase", 0x201E },
        { "quotedblleft", 0x201C },
        { "quotedblright", 0x201D },
        { "quoteleft", 0x2018 },
        { "quoteright", 0x2019 },
        { "quotesinglbase", 0x201A },
        { "quotesingle", 0x27 },
        { "R", 0x52 },
        { "r", 0x72 },
        { "ring", 0x02DA },
        { "S", 0x53 },
        { "s", 0x73 },
        { "section", 0x00A7 },
        { "semicolon", 0x003B },
        { "seven", 0x37 },
        { "six", 0x36 },
        { "slash", 0x002F },
        { "space", 0x20 },
        { "space", 0x00A0 },
        { "sterling", 0x00A3 },
        { "T", 0x54 },
        { "t", 0x74 },
        { "three", 0x33 },
        { "tilde", 0x02DC },
        { "two", 0x32 },
        { "U", 0x55 },
        { "u", 0x75 },
        { "underscore", 0x005F },
        { "V", 0x56 },
        { "v", 0x76 },
        { "W", 0x57 },
        { "w", 0x77 },
        { "X", 0x58 },
        { "x", 0x78 },
        { "Y", 0x59 },
        { "y", 0x79 },
        { "yen", 0x00A5 },
        { "Z", 0x005A },
        { "z", 0x007A },
        { "zero", 0x30 },
    };
} }
