#pragma once

#include <fontio/model/AdobeGlyphList.hpp>
#include <fontio/model/cff/ICffCharset.hpp>

namespace fontio { namespace model { namespace cff
{
    class CffIsoAdobeCharset : public ICffCharset
    {
    public:

        virtual const std::unordered_map<uint16_t, uint16_t>& GetGidToSidMap() const override
        {
            return GetMap();
        }

    private:

        static const std::unordered_map<uint16_t, uint16_t>& GetMap()
        {
            static std::unordered_map<uint16_t, uint16_t> map =
            {
                {1, UnicodeFromName("space")},
                {2, UnicodeFromName("exclam")},
                {3, UnicodeFromName("quotedbl")},
                {4, UnicodeFromName("numbersign")},
                {5, UnicodeFromName("dollar")},
                {6, UnicodeFromName("percent")},
                {7, UnicodeFromName("ampersand")},
                {8, UnicodeFromName("quoteright")},
                {9, UnicodeFromName("parenleft")},
                {10, UnicodeFromName("parenright")},
                {11, UnicodeFromName("asterisk")},
                {12, UnicodeFromName("plus")},
                {13, UnicodeFromName("comma")},
                {14, UnicodeFromName("hyphen")},
                {15, UnicodeFromName("period")},
                {16, UnicodeFromName("slash")},
                {17, UnicodeFromName("zero")},
                {18, UnicodeFromName("one")},
                {19, UnicodeFromName("two")},
                {20, UnicodeFromName("three")},
                {21, UnicodeFromName("four")},
                {22, UnicodeFromName("five")},
                {23, UnicodeFromName("six")},
                {24, UnicodeFromName("seven")},
                {25, UnicodeFromName("eight")},
                {26, UnicodeFromName("nine")},
                {27, UnicodeFromName("colon")},
                {28, UnicodeFromName("semicolon")},
                {29, UnicodeFromName("less")},
                {30, UnicodeFromName("equal")},
                {31, UnicodeFromName("greater")},
                {32, UnicodeFromName("question")},
                {33, UnicodeFromName("at")},
                {34, UnicodeFromName("A")},
                {35, UnicodeFromName("B")},
                {36, UnicodeFromName("C")},
                {37, UnicodeFromName("D")},
                {38, UnicodeFromName("E")},
                {39, UnicodeFromName("F")},
                {40, UnicodeFromName("G")},
                {41, UnicodeFromName("H")},
                {42, UnicodeFromName("I")},
                {43, UnicodeFromName("J")},
                {44, UnicodeFromName("K")},
                {45, UnicodeFromName("L")},
                {46, UnicodeFromName("M")},
                {47, UnicodeFromName("N")},
                {48, UnicodeFromName("O")},
                {49, UnicodeFromName("P")},
                {50, UnicodeFromName("Q")},
                {51, UnicodeFromName("R")},
                {52, UnicodeFromName("S")},
                {53, UnicodeFromName("T")},
                {54, UnicodeFromName("U")},
                {55, UnicodeFromName("V")},
                {56, UnicodeFromName("W")},
                {57, UnicodeFromName("X")},
                {58, UnicodeFromName("Y")},
                {59, UnicodeFromName("Z")},
                {60, UnicodeFromName("bracketleft")},
                {61, UnicodeFromName("backslash")},
                {62, UnicodeFromName("bracketright")},
                {63, UnicodeFromName("asciicircum")},
                {64, UnicodeFromName("underscore")},
                {65, UnicodeFromName("quoteleft")},
                {66, UnicodeFromName("a")},
                {67, UnicodeFromName("b")},
                {68, UnicodeFromName("c")},
                {69, UnicodeFromName("d")},
                {70, UnicodeFromName("e")},
                {71, UnicodeFromName("f")},
                {72, UnicodeFromName("g")},
                {73, UnicodeFromName("h")},
                {74, UnicodeFromName("i")},
                {75, UnicodeFromName("j")},
                {76, UnicodeFromName("k")},
                {77, UnicodeFromName("l")},
                {78, UnicodeFromName("m")},
                {79, UnicodeFromName("n")},
                {80, UnicodeFromName("o")},
                {81, UnicodeFromName("p")},
                {82, UnicodeFromName("q")},
                {83, UnicodeFromName("r")},
                {84, UnicodeFromName("s")},
                {85, UnicodeFromName("t")},
                {86, UnicodeFromName("u")},
                {87, UnicodeFromName("v")},
                {88, UnicodeFromName("w")},
                {89, UnicodeFromName("x")},
                {90, UnicodeFromName("y")},
                {91, UnicodeFromName("z")},
                {92, UnicodeFromName("braceleft")},
                {93, UnicodeFromName("bar")},
                {94, UnicodeFromName("braceright")},
                {95, UnicodeFromName("asciitilde")},
                {96, UnicodeFromName("exclamdown")},
                {97, UnicodeFromName("cent")},
                {98, UnicodeFromName("sterling")},
                {99, UnicodeFromName("fraction")},
                {100, UnicodeFromName("yen")},
                {101, UnicodeFromName("florin")},
                {102, UnicodeFromName("section")},
                {103, UnicodeFromName("currency")},
                {104, UnicodeFromName("quotesingle")},
                {105, UnicodeFromName("quotedblleft")},
                {106, UnicodeFromName("guillemotleft")},
                {107, UnicodeFromName("guilsinglleft")},
                {108, UnicodeFromName("guilsinglright")},
                {109, UnicodeFromName("fi")},
                {110, UnicodeFromName("fl")},
                {111, UnicodeFromName("endash")},
                {112, UnicodeFromName("dagger")},
                {113, UnicodeFromName("daggerdbl")},
                {114, UnicodeFromName("periodcentered")},
                {115, UnicodeFromName("paragraph")},
                {116, UnicodeFromName("bullet")},
                {117, UnicodeFromName("quotesinglbase")},
                {118, UnicodeFromName("quotedblbase")},
                {119, UnicodeFromName("quotedblright")},
                {120, UnicodeFromName("guillemotright")},
                {121, UnicodeFromName("ellipsis")},
                {122, UnicodeFromName("perthousand")},
                {123, UnicodeFromName("questiondown")},
                {124, UnicodeFromName("grave")},
                {125, UnicodeFromName("acute")},
                {126, UnicodeFromName("circumflex")},
                {127, UnicodeFromName("tilde")},
                {128, UnicodeFromName("macron")},
                {129, UnicodeFromName("breve")},
                {130, UnicodeFromName("dotaccent")},
                {131, UnicodeFromName("dieresis")},
                {132, UnicodeFromName("ring")},
                {133, UnicodeFromName("cedilla")},
                {134, UnicodeFromName("hungarumlaut")},
                {135, UnicodeFromName("ogonek")},
                {136, UnicodeFromName("caron")},
                {137, UnicodeFromName("emdash")},
                {138, UnicodeFromName("AE")},
                {139, UnicodeFromName("ordfeminine")},
                {140, UnicodeFromName("Lslash")},
                {141, UnicodeFromName("Oslash")},
                {142, UnicodeFromName("OE")},
                {143, UnicodeFromName("ordmasculine")},
                {144, UnicodeFromName("ae")},
                {145, UnicodeFromName("dotlessi")},
                {146, UnicodeFromName("lslash")},
                {147, UnicodeFromName("oslash")},
                {148, UnicodeFromName("oe")},
                {149, UnicodeFromName("germandbls")},
                {150, UnicodeFromName("onesuperior")},
                {151, UnicodeFromName("logicalnot")},
                {152, UnicodeFromName("mu")},
                {153, UnicodeFromName("trademark")},
                {154, UnicodeFromName("Eth")},
                {155, UnicodeFromName("onehalf")},
                {156, UnicodeFromName("plusminus")},
                {157, UnicodeFromName("Thorn")},
                {158, UnicodeFromName("onequarter")},
                {159, UnicodeFromName("divide")},
                {160, UnicodeFromName("brokenbar")},
                {161, UnicodeFromName("degree")},
                {162, UnicodeFromName("thorn")},
                {163, UnicodeFromName("threequarters")},
                {164, UnicodeFromName("twosuperior")},
                {165, UnicodeFromName("registered")},
                {166, UnicodeFromName("minus")},
                {167, UnicodeFromName("eth")},
                {168, UnicodeFromName("multiply")},
                {169, UnicodeFromName("threesuperior")},
                {170, UnicodeFromName("copyright")},
                {171, UnicodeFromName("Aacute")},
                {172, UnicodeFromName("Acircumflex")},
                {173, UnicodeFromName("Adieresis")},
                {174, UnicodeFromName("Agrave")},
                {175, UnicodeFromName("Aring")},
                {176, UnicodeFromName("Atilde")},
                {177, UnicodeFromName("Ccedilla")},
                {178, UnicodeFromName("Eacute")},
                {179, UnicodeFromName("Ecircumflex")},
                {180, UnicodeFromName("Edieresis")},
                {181, UnicodeFromName("Egrave")},
                {182, UnicodeFromName("Iacute")},
                {183, UnicodeFromName("Icircumflex")},
                {184, UnicodeFromName("Idieresis")},
                {185, UnicodeFromName("Igrave")},
                {186, UnicodeFromName("Ntilde")},
                {187, UnicodeFromName("Oacute")},
                {188, UnicodeFromName("Ocircumflex")},
                {189, UnicodeFromName("Odieresis")},
                {190, UnicodeFromName("Ograve")},
                {191, UnicodeFromName("Otilde")},
                {192, UnicodeFromName("Scaron")},
                {193, UnicodeFromName("Uacute")},
                {194, UnicodeFromName("Ucircumflex")},
                {195, UnicodeFromName("Udieresis")},
                {196, UnicodeFromName("Ugrave")},
                {197, UnicodeFromName("Yacute")},
                {198, UnicodeFromName("Ydieresis")},
                {199, UnicodeFromName("Zcaron")},
                {200, UnicodeFromName("aacute")},
                {201, UnicodeFromName("acircumflex")},
                {202, UnicodeFromName("adieresis")},
                {203, UnicodeFromName("agrave")},
                {204, UnicodeFromName("aring")},
                {205, UnicodeFromName("atilde")},
                {206, UnicodeFromName("ccedilla")},
                {207, UnicodeFromName("eacute")},
                {208, UnicodeFromName("ecircumflex")},
                {209, UnicodeFromName("edieresis")},
                {210, UnicodeFromName("egrave")},
                {211, UnicodeFromName("iacute")},
                {212, UnicodeFromName("icircumflex")},
                {213, UnicodeFromName("idieresis")},
                {214, UnicodeFromName("igrave")},
                {215, UnicodeFromName("ntilde")},
                {216, UnicodeFromName("oacute")},
                {217, UnicodeFromName("ocircumflex")},
                {218, UnicodeFromName("odieresis")},
                {219, UnicodeFromName("ograve")},
                {220, UnicodeFromName("otilde")},
                {221, UnicodeFromName("scaron")},
                {222, UnicodeFromName("uacute")},
                {223, UnicodeFromName("ucircumflex")},
                {224, UnicodeFromName("udieresis")},
                {225, UnicodeFromName("ugrave")},
                {226, UnicodeFromName("yacute")},
                {227, UnicodeFromName("ydieresis")},
                {228, UnicodeFromName("zcaron")}
            };

            return map;
        }

        static uint16_t UnicodeFromName(const std::string& name)
        {
            AdobeGlyphList glyphlist;

            return glyphlist.GetUnicode(name);
        }

    };
} } }
